update the clean up

diff --git a/.github/workflows/snyk-pr-cleanup.yml b/.github/workflows/snyk-pr-cleanup.yml
--- a/.github/workflows/snyk-pr-cleanup.yml
+++ b/.github/workflows/snyk-pr-cleanup.yml
@@ -1,7 +1,12 @@
-name: 🪥 Snyk PR cleanup - merged/closed
+name: 🪥 Snyk PR cleanup
 
-on: workflow_call  
-
+on: 
+  workflow_call:
+    secrets:
+      snyk_token:
+        required: true
+      snyk_org_id:
+        required: true
 env:
   SNYK_TAG_MAX_LENGTH: 50
 
@@ -18,11 +23,27 @@ jobs:
           if [[ ${GITHUB_EVENT_NAME} == "pull_request" ]]; then 
             REAL_BRANCH=$GITHUB_HEAD_REF 
           fi 
-          REAL_BRANCH=$(echo $REAL_BRANCH | cut -c1-${{ SNYK_TAG_MAX_LENGTH }})
-
-          # replace '/' with '_' for repo and branch names
+          
+          # snyk tag limitation - limit length to SNYK_TAG_MAX_LENGTH
+          REAL_BRANCH=$(echo $REAL_BRANCH | cut -c1-${{ env.SNYK_TAG_MAX_LENGTH }})  
+            
+          # snyk tag limitation - replace '/' with '_'
           TAG_REPO=${GITHUB_REPOSITORY//\//_}
           TAG_BRANCH=${REAL_BRANCH//\//_}
+
+          # snyk tag limitation - replace '.' with '-'
+          TAG_REPO=${TAG_REPO//./-}
+          TAG_BRANCH=${TAG_BRANCH//./-}
+          
+          echo "TAG_REPO = [$TAG_REPO]"        
+          echo "TAG_BRANCH = [$TAG_BRANCH]"
+          
+          # make sure on other unsupported characters
+          if  [[ "$TAG_BRANCH" =~ [^a-zA-Z0-9_/\.\-] ]]; then
+            echo "$TAG_BRANCH contains invalid characters for synk tags - only allow alphanumerics and '/', '.',  '-', '_' "
+            exit 2
+          fi 
+
           echo "TAG_REPO=${TAG_REPO}" >> $GITHUB_ENV
           echo "TAG_BRANCH=${TAG_BRANCH}" >> $GITHUB_ENV
           echo "SNYK_FILTER_FILE=_synk_filter.json" >> $GITHUB_ENV
@@ -51,13 +72,13 @@ jobs:
       - name: delete all snyk projects associated with this repo and the guarded branch
         run: |
           # retrieve all snyk project ids associated with this repo and the guarded branch
-          ids=$(curl -q -X POST -H "Authorization:${{ secrets.SNYK_TOKEN }}" -H "Content-Type:application/json" \
-                  -d "@${SNYK_FILTER_FILE}" https://snyk.io/api/v1/org/${{ secrets.SNYK_ORG_ID }}/projects  \
+          ids=$(curl -q -X POST -H "Authorization:${{ secrets.snyk_token }}" -H "Content-Type:application/json" \
+                  -d "@${SNYK_FILTER_FILE}" https://snyk.io/api/v1/org/${{ secrets.snyk_org_id }}/projects  \
                 | jq -r '.projects[].id' )
 
-          # remove the selected snyk project 
+          # remove the selected snyk project ß
           while read -r id; do
-            curl -i -X DELETE -H "Authorization:${{ secrets.SNYK_TOKEN }}" \
-              "https://snyk.io/api/v1/org/${{ secrets.SNYK_ORG_ID }}/project/$id"
+            curl -i -X DELETE -H "Authorization:${{ secrets.snyk_token }}" \
+              "https://snyk.io/api/v1/org/${{ secrets.snyk_org_id }}/project/$id"
             echo "deleted snyk project id = [$id]"
           done <<< "$ids"                 
